In [16]:
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn import datasets
from scipy.spatial import distance

iris = datasets.load_iris()

iris_data = iris.data
iris_labels = iris.target

print(iris_data[30:100])
print(iris_labels[30:100])

[[4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.  1.3]
 [6.5 2.8 4.6 1.5]
 [5.7 2.8 4.5 1.3]
 [6.3 3.3 4.7 1.6]
 [4.9 2.4 3.3 1. ]
 [6.6 2.9 4.6 1.3]
 [5.2 2.7 3.9 1.4]
 [5.  2.  3.5 1. ]
 [5.9 3.  4.2 1.5]
 [6.  2.2 4.  1. ]
 [6.1 2.9 4.7 1.4]
 [5.6 2.9 3.6 1.3]
 [6.7 3.1 4.4 1.4]
 [5.6 3.  4.5 1.5]
 [5.8 2.7 4.1 1. ]
 [6.2 2.2 4.5 1.5]
 [5.6 2.5 3.9 1.1]
 [5.9 3.2 4.8 1.8]
 [6.1 2.8 4.  1.3]
 [6.3 2.5 4.9 1.5]
 [6.1 2.8 4.7 1.2]
 [6.4 2.9 4.3 1.3]
 [6.6 3.  4.4 1.4]
 [6.8 2.8 4.8 1.4]
 [6.7 3.  5.  1.7]
 [6.  2.9 4.5 1.5]
 [5.7 2.6 3.5 1. ]
 [5.5 2.4 3.8 1.1]
 [5.5 2.4 3.7 1. ]
 [5.8 2.7 3.

In [29]:
neigh = KNeighborsClassifier(n_neighbors=15)
neigh.fit(iris_data, iris_labels)

KNeighborsClassifier(n_neighbors=15)

In [30]:
print(neigh.predict([[5.6, 2.5, 4.1,  1.1]]))

[1]


In [27]:
def compute_distances(point, points):
    # Compute the distance between the point and every point of the dataset
    distances = []
    for p in points:
        # euclidean distance
        distances.append(distance.euclidean(p, point))
        
    return distances

def get_index(arr, el):
    # index of value in array 
    return arr.index(el)

def get_k_lowest(arr, k, skip_zero=True):
    # Get the k lowest values in an array
    lowest = []
    for val in arr:
        if len(lowest) < k and val != 0:
            # If fewer than k values, append
            lowest.append(val)
        elif val < max(lowest) and val != 0:
            # Replace largest value
            lowest[lowest.index(max(lowest))] = val
            
    return lowest
    
def get_k_nearest(distances, labels, k):
    votes =  []
    lowest = get_k_lowest(distances, k)
    for val in lowest:
        votes.append(labels[get_index(distances, val)])
        
    return votes

def summarize_votes(votes):
    # Count number of labels in votes array
    labels = {}
    for v in votes:
        if v not in labels:
            # initialize counter
            labels[v] = 1
        else:
            labels[v] = labels[v] + 1
            
    print(labels)
    return labels
    
def knn(point, points, labels, k):
    d = compute_distances(point, points)
    votes = get_k_nearest(d, labels, k)
    
    summarize_votes(votes)
    
    

In [31]:
k = 15
knn([[4.8, 3.1, 1.6, 0.2]], iris_data, iris_labels, k)

{0: 15}
